name: CI Pipeline
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 . --max-line-length=88 --extend-ignore=E203
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install pytest
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/ -v
  docker:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: docker build -t credit-risk-api .
      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name test-api credit-risk-api
          sleep 10
      - name: Test API endpoint
        run: |
          curl -X POST "http://localhost:8000/predict/" -H "Content-Type: application/json" -d '[{"LogMonetary": 10.0, "Frequency": 5, "LogAvgTransactionAmount": 2.5, "NightRatio": 0.1, "Freq_FinancialServices": 1, "Freq_Airtime": 2}]'
      - name: Stop Docker container
        run: docker stop test-api
      - name: Remove Docker container
        run: docker rm test-api